package group.compilatreur.al;

public enum CategorieLexical {
    INT, FLOAT, ADD, AFFECT, SUB, DIV, MOD, MUL, INF, SUP, ACOLADOUV, ACOLADFERM,REPETER,
    CROCHEOUV, CROCHEFERM, NOT, APOSTROF, SUPEGAL, INFEGAL, EGAL, GRIFFE, INC, DEC, CMTLIGNE, AND,
    PARENTOUV, PARENTHFERM,VIRGULE,PRINT, SCAN,STRING,TEXT, BEGIN, END, CMLMULTILIGNE,
    OR, DIFF, SI, SINON, SINONSI, TANTQUE, CONSTANTE, IDENT, ENDLINE, ENTIER, REEL, LETTRE, DEBCMT, FINCMT, BOOLEAN, UNDEFINED
}
